web_system/image_handle/urls.py
# -*- coding: utf-8 -*-
# FileName  : urls.py

from django.urls import path
from . import views

app_name = 'image_handle'
urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.check, name='check'),
    path('upload_img/', views.upload_img, name='upload_img'),
    path('check_img/', views.check_img, name='check_img'),
]


web_system/image_handle/models.py
from django.db import models


class ImageCheck(models.Model):
    file_name = models.CharField(max_length=200, verbose_name='图片名')
    file_url = models.CharField(max_length=250, verbose_name='图片URL')
    check_result = models.CharField(max_length=100, verbose_name='识别结果', blank=True)
    check_time = models.DateTimeField(auto_now_add=True, verbose_name='检测时间')

    class Meta:
        db_table = 'image_check'
        verbose_name = '图片检测'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.file_name

web_system/image_handle/views.py
import os
from django.conf import settings
from django.shortcuts import render
from .models import ImageCheck
from django.http import JsonResponse
from utils.image_check import check_handle
from web_system.settings import admin_title, index_info
import time


def index(request):
    context = {
        'title': admin_title,
        'index_info': index_info
    }

    return render(request, 'index.html', context=context)


def check(request):
    return render(request, 'check.html')


def upload_img(request):
    # 图片上传
    file = request.FILES.get('file')
    image_name = file.name
    file_name = '{}.{}'.format(int(time.time()), str(image_name).rsplit('.')[-1])
    with open(os.path.join(settings.MEDIA_ROOT, file_name), 'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    upload_url = request.build_absolute_uri(settings.MEDIA_URL + file_name)
    ImageCheck.objects.create(file_name=file_name, file_url=upload_url)
    return JsonResponse({'code': 200, 'data': {'url': upload_url}})


def check_img(request):
    # 图片检测
    image_url = request.POST.get('img_url')
    if not image_url:
        return JsonResponse({'code': 400, 'message': '缺少必传的参数'})
    image_name = image_url.rsplit('/')[-1]
    image_path = os.path.join(settings.MEDIA_ROOT, image_name)
    pred_name = check_handle(image_path)

    obj = ImageCheck.objects.filter(file_name=image_name).last()
    obj.check_result = pred_name
    obj.save()
    return JsonResponse({'code': 200, 'data': {'pred_name': pred_name}})

web_system/front/templates/check.html
{% extends 'front_base.html' %}

{% block title %}
    使用
{% endblock %}

{% block header %}
    <script src="{% static 'js/check.js' %}"></script>
    <style>
        .input-image {
            width: 500px;
            height: 400px;
            float: left;
            margin-top: 58px;
        }

        .input-image img {
            width: 100%;
            height: 100%;
        }

        .input-image span {
            margin-left: 100px
        }
    </style>
{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>上传一张图片进行识别</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form action="" class="form-group">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="thumbnail-form">上传图片</label>
                            <div class="input-group">

                                <input type="text" class="form-control" id="img-url" name="img_url">
                                <input type="file" id="upload-btn" value="上传图片" style="float: right;margin-top: 20px" class="btn">

                            </div>
                        </div>

                        <button class="btn btn-primary pull-right" id="img-change">检测</button>
                        <div class="input-image">
                            <span>上传的图片</span>
                            <img src="{% static 'image/check_logo.jpg' %}" alt=""
                                 class="input-image-file">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web_system/front/templates/front_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--视口设置，适配移动端-->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>识别系统{% block title %}{% endblock %}</title>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/myalert.js' %}"></script>

    {% block header %}

    {% endblock %}

</head>
<body>
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">

        <!--定义菜单-->
        <div class="collapse navbar-collapse" id="mymenu">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'image_handle:index' %}">简介</a>
                </li>

                <li>
                    <a href="{% url 'image_handle:check' %}">检测</a>
                </li>
                <li>
                    <a href="/admin/" target="_blank">后台管理</a>
                </li>
            </ul>

        </div>
    </div>
</div>


<div class="main">
    <div class="container">
        {% block main-container %}

        {% endblock %}
    </div>
</div>

<div class="footer" style="background-color: #012030">
    <div class="container">
        <div class="row footer-top">
            <div class="col-sm-6 col-lg-6">
                <h4></h4>
            </div>
            <div class="col-sm-6  col-lg-5 col-lg-offset-1">
                <div class="row about"></div>

            </div>
        </div>
        <hr>
        <div class="row footer-bottom">
        </div>
    </div>
</div>
</body>
</html>

web_system/front/templates/index.html
{% extends 'front_base.html' %}

{% block title %}
    首页
{% endblock %}


{% block header %}

{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>{{ title }}
                <small></small>
            </h1>
        </div>
        <div class="box-body">
            <div class="box-info">
                <div class="info-image">
                    <div class="box-image">
                        <img src="{% static 'image/index1.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/index2.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/index3.jpg' %}" alt="">
                    </div>
                </div>
                <div class="box-content">
                    <p>
                        {{ index_info }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}